# This workflow will lint python code

name: my linter
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Lint with flake8
      run: |
        poetry run flake8 brain_games
