# This workflow will lint python code

name: my linter
on: push
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      # make depends on poetry
    - name: Install dependencies
      run: |
        pip install poetry
        make install
    - name: Lint with flake8
      run: |
        make lint
